### ISSUE TITLE
Readme.md not updated

### ISSUE THREAD

**Issue by yuananf** [xerial/presto-metrics#1]
client.get_json("java.lang:Type=Memory") throws error, 
should be client.get_mbean_json("java.lang:Type=Memory")

"non_heap_memory_usage": {
#    "committed": 163250176,
#    "init": 159842304,
#    "max": 471859200,
#    "used": 53369528
3  },

should be
"non_heap_memory_usage": {
#    "committed": 163250176,
#    "init": 159842304,
#    "max": 471859200,
#    "used": 533695283
#},

**Comment by xerial** [comment]
Thanks. I'll fix this.
